### PR TITLE
add wysihtml5 support for bootstrap 3

### PR DESCRIPTION
**Pull request by Madao-3**

### CODE REVIEW

**Comment by Madao-3** [comment]
@lorvent Vitaliy Potapov told me to metion you.

**Comment by rbruhn** [comment]
do you have an example of this working somewhere? For the life of me, I can't get this to work even with the simple example:
```
<div id="comments" data-type="wysihtml5" data-pk="1"><h2>awesome</h2> comment!</div>
<script>
$(function(){
    $('#comments').editable({
        url: '/post',
        title: 'Enter comments'
    });
});
</script>
```
The edit box shows but the editor does not appear.

**Comment by lorvent** [comment]
Sorry, somehow i missed your mention

can you show working example, as pointed out by @rbruhn 

thanks.

**Comment by MarQuisKnox** [comment]
Demo:  http://madao-3.github.io/x-editable/demo-bs3.html

**Pull request merged**
