### PR TITLE
WYSIHTML5 support for bootstrap 3 and fix input type number bug

### PR DESCRIPTION
**Pull request by Madao-3**
if the input's type is number, it will trigger a Error:

>  Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

### CODE REVIEW

**Comment by Madao-3** [comment]
Now i add WYSIHTML5 support for bootstrap 3!

**Comment by Madao-3** [comment]
@vitalets

**Comment by Madao-3** [comment]
also update gh-pages's doc.

**Comment by Madao-3** [comment]
http://Madao-3.github.io/x-editable/demo-bs3.html

**Comment by Madao-3** [comment]
@lorvent Vitaliy Potapov told me to metion you.

**Comment by ikerib** [comment]
Hi!
I need these feature and it works ok but when I clicked in the .editable field y performs a "jump" and I have to scroll a little bit to the top to see the editable form

```
<div href="#" class="editable2 text-left" data-name="kontzeptuaeu" data-pk="22" data-url="/post/3"  data-type="wysihtml5">
 lorem impsum..
</div>
```

```
            $('.editable2').on('mouseover',function(){
                $(this).addClass('gainean');
            })
            .on('mouseleave',function(){
                $(this).removeClass('gainean');
            }).editable({
                title: 'Enter comments',
                showbuttons: 'top',
                wysihtml5: {
                    "image": false,
                    "font-styles": false, //Font styling, e.g. h1, h2, etc. Default true
                    "emphasis": true, //Italics, bold, etc. Default true
                    "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
                    "html": false, //Button which allows you to edit the generated HTML. Default false
                    "link": false, //Button to insert a link. Default true
                }
            });
```

do you know why?

**Pull request closed without merging**
