### PR TITLE
update gradient direction syntax

### PR DESCRIPTION
**Pull request by YannickBochatay**
CSS gradients had outdated direction syntax. New syntax is like `to bottom` instead of `top`.
Prefixed properties have not been changed.

### CODE REVIEW

**Comment by YannickBochatay** [comment]
https://drafts.csswg.org/css-images-3/#linear-gradients
Apparently it's still a draft, but stable.
There is some information on MDN : 
https://developer.mozilla.org/en/docs/Web/CSS/linear-gradient

**Comment by MarQuisKnox** [comment]
Thanks for the info & the PR, but we are not going to support this right now. 

1. http://www.quirksmode.org/css/images/gradients_desktop.html
2. http://www.w3schools.com/css/css3_gradients.asp

**Comment by bbashy** [comment]
Just got compile warnings for this.

```
 WARNING  Compiled with 5 warnings                                                                                                                                                      10:47:10

 warning  in ./resources/assets/sass/app.scss

(Emitted value instead of an instance of Error) autoprefixer: /path/to/project/assets/sass/app.scss:136:5: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
```

**Comment by bbashy** [comment]
Can this be updated/fixed now? Need a new PR by the looks of it.

**Pull request closed without merging**
